{
 "title": "Errors overview",
 "time": { "from": "2023-08-13T18:54:03.562Z", "to": "2023-08-13T21:51:59.992Z" },
 "templating": {
  "list": [
   {
    "name": "test_id",
    "query": "{\"find\": \"terms\", \"field\": \"testId.keyword\", \"query\": \"type.keyword: request\"}"
   },
   {
    "name": "phase",
    "query": "{\"find\": \"terms\", \"field\": \"phase.keyword\", \"query\": \"testId.keyword:$test_id AND type.keyword: request\"}"
   },
   { "name": "type", "query": "request, transaction" }
  ]
 },
 "panels": [
  {
   "title": "Tests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "testId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "type": "max" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword: request AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "{{type.keyword}}s per second",
     "bucketAggs": [
      {
       "field": "type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "settings": { "script": "_value/60" }, "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall request response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{metric}} RT",
     "bucketAggs": [
      {
       "field": "testId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" },
      {
       "field": "elapsed",
       "id": "4",
       "settings": {
        "percents": [
         "50",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed $type by Name for $test_id test(s)",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "failed", "id": "1", "type": "sum" },
      { "field": "hit", "id": "8", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed $type by code for $test_id test(s)",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "responseCode.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "failed",
       "hide": false,
       "id": "1",
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND failed:1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed $type by Use case for $test_id test(s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "useCase.keyword",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "failed", "id": "1", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND failed: 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed $type by ZooId for $test_id test(s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "zooId.keyword",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "failed", "id": "1", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND failed: 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Failed $type by Use case for $test_id test(s)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "responseCode.keyword",
       "id": "9",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "failed", "id": "1", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND failed: 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "$type Errors breakdown for $test_id test(s)",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "metrics": [
      { "id": "8", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "testId.keyword:$test_id AND type.keyword:$type AND phase.keyword:$phase AND failed:1",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}