{
 "title": "Requests timeline",
 "time": { "from": "2023-08-13T18:54:03.562Z", "to": "2023-08-13T21:51:59.992Z" },
 "templating": {
  "list": [
   {
    "name": "test_id",
    "query": "{\"find\": \"terms\", \"field\": \"testId.keyword\", \"query\": \"type.keyword: request\"}"
   },
   {
    "name": "phase",
    "query": "{\"find\": \"terms\", \"field\": \"phase.keyword\", \"query\": \"testId.keyword:$test_id AND type.keyword: request\"}"
   },
   { "name": "type", "query": "request, transaction" },
   {
    "name": "name",
    "query": "{\"find\": \"terms\", \"field\": \"name.keyword\", \"query\": \"testId.keyword:$test_id AND phase.keyword: $phase AND type.keyword: $type\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Tests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "testId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "type": "max" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword: request AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall request response time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{metric}} RT",
     "bucketAggs": [
      {
       "field": "testId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" },
      {
       "field": "elapsed",
       "id": "4",
       "settings": {
        "percents": [
         "50",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall requests per second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "{{type.keyword}}s per second",
     "bucketAggs": [
      {
       "field": "type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "settings": { "script": "_value/60" }, "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall $type incoming/outgoing traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "bytes", "id": "1", "settings": { "script": "_value/60" }, "type": "sum" },
      { "field": "sentBytes", "id": "3", "settings": { "script": "_value/60" }, "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall errors per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Errors/min",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "failed", "id": "1", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND type.keyword: $type",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND name.keyword: $name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Response time 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[95.0]", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "settings": { "percents": [ "95" ] }, "type": "percentiles" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND name.keyword: $name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Median response time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1[95.0]", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "settings": { "percents": [ "50" ] }, "type": "percentiles" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase AND name.keyword: $name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Requests per second breakdown",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "{{name.keyword}}s per second",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "settings": { "script": "_value/60" }, "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND type.keyword: $type AND name.keyword: $name",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Errors per minute breakdown",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{name.keyword}} error",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "failed", "id": "1", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND type.keyword: $type",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}