{
 "title": "Transaction details",
 "time": { "from": "2023-08-13T18:54:03.562Z", "to": "2023-08-13T21:51:59.992Z" },
 "templating": {
  "list": [
   {
    "name": "test_id",
    "query": "{\"find\": \"terms\", \"field\": \"testId.keyword\", \"query\": \"type.keyword: request\"}"
   },
   {
    "name": "phase",
    "query": "{\"find\": \"terms\", \"field\": \"phase.keyword\", \"query\": \"testId.keyword:$test_id AND type.keyword: request\"}"
   },
   {
    "name": "name",
    "query": "{\"find\": \"terms\", \"field\": \"name.keyword\", \"query\": \"testId.keyword:$test_id AND type.keyword: transaction AND phase.keyword:$phase\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Tests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "testId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "type": "max" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword: request AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall requests per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "{{type.keyword}}s per second",
     "bucketAggs": [
      {
       "field": "type.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "hit", "id": "1", "settings": { "script": "_value/60" }, "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Overall request response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{metric}} RT",
     "bucketAggs": [
      {
       "field": "testId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" },
      {
       "field": "elapsed",
       "id": "4",
       "settings": {
        "percents": [
         "50",
         "95"
        ]
       },
       "type": "percentiles"
      }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    },
    {
     "alias": "VU",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1m", "min_doc_count": "1" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "grpThreads", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND type.keyword:$type AND phase.keyword: $phase",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request metrics by transaction for $name ",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" },
      {
       "field": "elapsed",
       "id": "4",
       "settings": {
        "percents": [
         "50",
         "95"
        ]
       },
       "type": "percentiles"
      },
      {
       "field": "elapsed",
       "id": "5",
       "meta": {
        "count": true,
        "max": true,
        "min": true,
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "type": "extended_stats"
      },
      { "field": "bytes", "id": "6", "type": "avg" },
      { "field": "sentBytes", "id": "7", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND transactionName.keyword:$name",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "failed", "id": "8", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND transactionName.keyword:$name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request metrics by transaction for $name ",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "4",
       "settings": { "interval": "1d", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND transactionName.keyword:$name AND type: request",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request metrics by ZooId for $name ",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "zooId.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "elapsed", "id": "1", "type": "avg" },
      {
       "field": "elapsed",
       "id": "4",
       "settings": {
        "percents": [
         "50",
         "95"
        ]
       },
       "type": "percentiles"
      },
      {
       "field": "elapsed",
       "id": "5",
       "meta": {
        "count": true,
        "max": true,
        "min": true,
        "std_deviation": true,
        "std_deviation_bounds_lower": false,
        "std_deviation_bounds_upper": false
       },
       "type": "extended_stats"
      },
      { "field": "bytes", "id": "6", "type": "avg" },
      { "field": "sentBytes", "id": "7", "type": "avg" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND name.keyword:$name",
     "timeField": "@timestamp"
    },
    {
     "alias": "{{name.keyword}}",
     "bucketAggs": [
      {
       "field": "zooId.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": "1",
        "missing": "0",
        "order": "desc",
        "orderBy": "_term",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "failed", "id": "8", "type": "sum" }
     ],
     "query": "testId.keyword: $test_id AND phase.keyword: $phase AND name.keyword:$name",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}